In [1]:
# Importar librerías
import pandas as pd

Vamos a trabajar con un dataset de notas de un curso en el cual los alumnos fueron evaluados mediante tres trabajos prácticos

# 1. Analisis inicial de datos

Deben haber descargado y poner en su google drive el archivo *notas_maestria.csv*.

Luego monten su drive en la notebook para poder acceder al archivo

In [2]:
# Leemos el archivo
notas = pd.read_csv("../Datasets/notas_maestria.csv")

In [3]:
# Observamos las dimensiones del dataset
notas.shape

(68, 6)

In [4]:
# Vemos las columnas
notas.columns

Index(['ID', 'Título', 'Universidad', 'TP1', 'TP2', 'TP3'], dtype='object')

In [5]:
# Observamos las primeras filas del dataset 
notas.head()

   ID                        Título             Universidad   TP1   TP2   TP3
0   1      Ingeniero en Informatica      Univ. de la Sabana  55.0  65.0  77.5
1   2  Licenciado en Adminsitracion                     UBA  70.0  85.5  81.0
2   3     Ingenieria en Informatica  Universidad de Palermo  50.0  75.0  82.5
3   4       Licenciado en Geofisica   Univ Nacional del Sur  70.0  74.5  83.5
4   5      ingeniero en informatica                     UBA  97.5  85.0  90.0

1. **¿Cuáles son las observaciones?**

  

2. **¿Cuáles son las variables?**

Las observaciones son sobre los estudiantes que obtuvieon  un titulo, segun los trabajos practicos en cada universidad
Las variables son titulo,universidad y las notas de esos trabajos

# Analisis de datos

La profesora titular nos pide que respondamos las siguientes preguntas sobre el curso:

### a. ¿De cuáles universidades vienen los personas?

In [6]:
notas['Universidad'].str.upper().unique()

array(['UNIV. DE LA SABANA', 'UBA', 'UNIVERSIDAD DE PALERMO',
       'UNIV NACIONAL DEL SUR', 'ITBA', 'UNIVERSIDAD NACIONAL DE CUYO',
       'CAECE', 'UTN', 'UNIV.NACIONAL DE LUJAN', 'UADE',
       'UNIVERSIDAD NACIONAL DE GENERAL SARMIENTO',
       'UNIV NAC DE LA PLATA', 'UCEMA', 'UTN-FRH',
       'UNIVERSIDAD DE BARCELONA', 'UNIVERSIDAD NACIONAL DE COLOMBIA',
       'UNIVERSIDAD AUSTRAL', 'UNIV CATOLICA ARGENTINA'], dtype=object)

### b. ¿Qué carreras estudiaron las personas que provienen de la UTN?

In [7]:
condicion = notas['Universidad'].str.upper()=='UTN'
notas[condicion]['Título'].str.upper().unique()

array(['INGENIERIA ELECTRONICA',
       'INGENIERO EN SISTEMAS DE LA INFORMACION',
       'INGENIERIA EN SISTEMAS DE INFORMACION', 'INGENIERO INDUSTRIAL'],
      dtype=object)

### c. ¿Cuáles personas tienen una nota mayor o igual a 85 en los trabajos practicos 1 y 2 e inferior a 70 en el trabajo practico 3?

In [8]:
condicion1 = notas['TP1'] >= 85
condicion2 = notas['TP2'] >= 85
condicion3 = notas['TP3'] < 70
notas[condicion1 & condicion2 & condicion3]['ID']

6    7
Name: ID, dtype: int64

### d. ¿En cuáles trabajos prácticos cada persona se saco una nota igual o superior a 95?

Consideremos si es posible responder esta pregunta facilmente con esta forma del dataset

# 3. Tidy data

Recordemos que las condiciones para que un dataset se considere ordenado (tidy) son:

* Cada variable forma ______
* Cada observación forma _______
* Cada tipo de unidad observacional forma _________

¿El dataset de notas cumple con estas condiciones?

In [9]:
# Creamos nuestro dataset tidy
notas_tidy = pd.melt(notas,
                        id_vars = [	'ID', 'Título', 'Universidad'],
                        var_name='Trabajo',
                        value_name='Nota')
notas_tidy

,ID,Título,Universidad,Trabajo,Nota
0,1,Ingeniero en Informatica,Univ. de la Sabana,TP1,55.0
1,2,Licenciado en Adminsitracion,UBA,TP1,70.0
2,3,Ingenieria en Informatica,Universidad de Palermo,TP1,50.0
3,4,Licenciado en Geofisica,Univ Nacional del Sur,TP1,70.0
4,5,ingeniero en informatica,UBA,TP1,97.5
...,...,...,...,...,...
199,68,Licenciatura en Sistemas de Informacion,UBA,TP3,83.0
200,69,Ingenieria en Sistemas de Informacion,UTN,TP3,50.0
201,70,ingeniero industrial,UTN,TP3,40.0
202,71,Licenciatura en Analisis de Sistemas,UBA,TP3,92.5
203,72,licenciado en sistemas de informacion de las o...,UBA,TP3,70.0

In [10]:
# Dimensiones del dataset
notas_tidy.shape

(204, 5)

Ahora podemos contestar la pregunta:

¿En cuáles trabajos prácticos cada persona se saco una nota igual o superior a 95?

In [11]:
condicion = notas_tidy['Nota']>=95
notas_tidy.loc[condicion, ['ID','Trabajo','Nota']].sort_values(by=['ID','Trabajo','Nota'],ascending=[True,True,False])

     ID Trabajo   Nota
4     5     TP1   97.5
74    7     TP2  100.0
144   9     TP3   97.5
17   18     TP1  100.0
85   18     TP2   97.5
18   19     TP1   95.0
19   20     TP1   95.0
87   20     TP2   96.0
157  22     TP3   95.0
159  24     TP3   95.0
27   28     TP1   95.0
28   29     TP1   96.5
31   32     TP1   95.0
103  36     TP2   95.0
171  36     TP3   95.0
37   39     TP1   95.0
173  39     TP3  100.0
39   41     TP1   97.0
175  41     TP3   95.0
186  52     TP3   97.5
188  54     TP3   97.5
189  56     TP3   95.0
191  60     TP3   95.0
58   63     TP1  100.0
60   65     TP1  100.0
66   71     TP1  100.0
134  71     TP2  100.0

## Opcionales

### ¿Cuantos trabajos prácticos de cada tipo tuvieron una nota igual o superior a 95 puntos?

In [12]:
condicion = notas_tidy['Nota'] >= 95
notas_tidy.loc[condicion, ['Trabajo']].groupby('Trabajo', group_keys=False).agg(
    {
        'Trabajo':[("Cantidad","count")]
    }
)

         Trabajo
        Cantidad
Trabajo
TP1           12
TP2            5
TP3           10

### ¿Cuál fue la nota promedio por cada trabajo práctico?

In [15]:
notas_tidy.loc[condicion, ['Trabajo','Nota']].groupby('Trabajo').agg(
    {
        'Nota': [("Promedio", "mean")]
    }
).sort_values(by='Nota',ascending = False)

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'